AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  logs_access

  Sample SAM Template for logs_access

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    Timeout: 180

Resources:
  SeeqLogsAccessFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      CodeUri: seeq_logs_access/
      Handler: app.lambda_handler
      Runtime: python3.11
      Architectures:
        - x86_64
      Events:
        SeeqLogsAccess:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /SqLogsAccess
            Method: get

Outputs:
  # ServerlessRestApi is an implicit API created out of Events key under Serverless::Function
  # Find out more about other implicit resources you can reference within SAM
  # https://github.com/awslabs/serverless-application-model/blob/master/docs/internals/generated_resources.rst#api
  SeeqLogsAccessApi:
    Description: "API Gateway endpoint URL for Prod stage for Seeq Logs Access function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/hello/"
  SeeqLogsAccessFunction:
    Description: "Seeq Logs Access Lambda Function ARN"
    Value: !GetAtt SeeqLogsAccessFunction.Arn
  SeeqLogsAccessIamRole:
    Description: "Implicit IAM Role created for Seeq Logs Access function"
    Value: !GetAtt SeeqLogsAccessFunctionRole.Arn
